# This file should "COntain all the re"COrd creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed "COmmand (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

patch_types = [
"AÉÉTS AGENDA",
"AÉÉTS ATHLETS",
"AÉÉTS CA",
"AÉÉTS CE",
"AÉÉTS CECS",
"AÉÉTS CECTN",
"AÉÉTS CECUT",
"AÉÉTS CEELE",
"AÉÉTS CEGPA",
"AÉÉTS CEGTI",
"AÉÉTS CELOG",
"AÉÉTS CEMEC",
"AÉÉTS CJS",
"AÉÉTS CQI",
"AÉÉTS DCI",
"AÉÉTS JDG",
"AÉÉTS PROMO",
"AÉÉTS RADIO",
"AÉÉTS RSG",
"AÉÉTS TRIBU",
"AEROETS CE",
"CLUB ABD",
"CLUB ACE",
"CLUB APPLETS",
"CLUB BAJA",
"CLUB CANOE",
"CLUB CAPRA",
"CLUB CEDILLE",
"CLUB CHINOOK",
"CLUB CONJURE",
"CLUB DRONOLAB",
"CLUB ECLIPSE",
"CLUB EVO",
"CLUB FORMULE",
"CLUB GÉNIALE",
"CLUB GI-ETS",
"CLUB HERCULE",
"CLUB IEEE",
"CLUB NAOVA",
"CLUB OMER",
"CLUB PHOTON",
"CLUB QUIETS",
"CLUB ROCKETS",
"CLUB SONIA",
"CLUB VE2",
"CLUB WALKING",
"CO CCI",
"CO CQI",
"CO CS GAMES",
"CO IISE",
"CO JDG",
"ETS CSSE",
"ORG FETSIVAL",
"ORG R&D",
"ORG RENTREE",
"SAE BIG BAND",
"SAE CRABE",
"SAE DEBAT PIR.",
"SAE DECOUVE",
"SAE E-SPORTS",
"SAE ETS SPEC",
"SAE ETSPERANTO",
"SAE INTEGRALE",
"SAE JEUX",
"SAE LAN",
"SAE LIETS",
"SAE PARRAINAGE",
"SAE PHOENIX",
"SAE PRECI",
"SAE RAFALE",
"SAE REFLETS",
"SAE RUGBY",
"SAE TENNIS",
"SAE VOLLEY",
"SAE TURBULE",
"BACC CTN",
"BACC MEC",
"BACC ÉLÉ",
"BACC LOG",
"BACC TI",
"BACC GOL",
"BACC GPA",
"MAIT MEC",
"MAIT CTN",
"MAIT ÉLÉ",
"MAIT LOG",
"MAIT TI",
"MAIT GOL",
"MAIT GPA",
"MAIT AERO",
"MAIT ENV",
"MAIT CONC",
"MAIT ENR",
"MAIT RSST"
"MAIT INOV",
"MAIT RT",
"MAIT TS",
"DOC MEC",
"DOC ÉLÉ",
"DOC CTN",
"DOC LOG",
"DOC TI",
"DOC GPA",
"DOC GOL"
]

patch_types.each do |patch_type|
    PatchType.create(name: patch_type, description: "Lorem Ipsum")